spring.application.name=discografia

server.port=8081


spring.mongodb.uri=mongodb+srv://carlosmoreira_db_user:Holahola123@cluster-spring.ut2txck.mongodb.net/discografia-db?retryWrites=true&w=majority